### ISSUE TITLE
Is the UK Constituency count correct?

### ISSUE THREAD

**Issue by j-f-d** [academe/parliament-petition-monitor#1]
[241584.txt](https://github.com/academe/parliament-petition-monitor/files/2995775/241584.txt)

https://petitions.acadweb.co.uk/overview/241584

2,668,994 (1,238,638 for UK constituencies)

Looking at the JSON data, the number for UK constituencies seems to be massively under counted.

**Comment by judgej** [comment]
Hi - yes - it seems to have halted about 8pm last night. I think the petitions site is either a bit broken and they have not fixed it yet, or they have turned the processes to keep the totals up-to-date off due to the load.

I have addeded a percentage figure to the results, and for other petitions you can see sits at between 93% and 97%. These are votes which have a postcode that has been matched to a constituency. I could also show counts of votes by UK/EC/other, but the main petitions site already does that nicely.

**Comment by j-f-d** [comment]
Nah, so if it is broken data, it doesn't make sense to fudge your program.

However, if the graphs showed the number of declared UK constituency numbers and the other regions in different colours on the graphs, that might help. In this case, if that was shown on the delta graph, it would make it clear that they aren't updating the numbers anymore, so you would need to 'go grey' when they aren't giving the data.

**Comment by judgej** [comment]
Yes, good idea. You could see where they diverge. The historic data for showing that is all in the database, so I can do that. Could show UK/non-UK in the same way.

As for fudging data, I hope it dodn't sound like I was suggesting that ;-) The system stores a snapshot every N minutes of what the petitions site provides and that is it. I do round the times to the nearest five minutes on the X-axis just to make the labels easier to read, but that's all the fudging that happens.

Busy day today (and I need to think about full-page cacheing too) but hopefully can take a look at your suggestion this evening.

**Comment by j-f-d** [comment]
Thanks

**Comment by judgej** [comment]
@j-f-d take a look - see what you think.

**Comment by j-f-d** [comment]
Looks great. Seems like the counts have been moving again, but you can clearly see what happened.
